
[brick]
chplVersion = "1.25.0"
license = "None"
name = "myMasonPackage"
type="application"
version = "0.1.0"

[dependencies]
DataStructures = "0.1.0"
NumpyLike = "0.1.0"

[dependencies.SymArrayDmap]
git = "https://github.com/bmcdonald3/SymArrayDmap"


